# Generated by Django 5.1.2 on 2024-11-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customsuser_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customsuser",
            options={
                "permissions": [
                    ("can_manage_users", "can manage users"),
                    ("can_block_users", "can block users"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="customsuser",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
