# Generated by Django 5.1.2 on 2024-11-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customsuser_options_customsuser_is_blocked"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customsuser",
            options={
                "permissions": [("can_block_user", "Может блокировать пользователя")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
