# Generated by Django 5.1.2 on 2024-11-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customsuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customsuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите аватар",
                null=True,
                upload_to="photo/avatar",
                verbose_name="Аватар",
            ),
        ),
    ]
