# Generated by Django 5.1.2 on 2024-11-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_mailing_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="is_active",
        ),
    ]
