# Generated by Django 5.1.2 on 2024-11-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_remove_mailing_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "Создана"),
                    ("running", "Запущена"),
                    ("completed", "Завершена"),
                    ("deactivated", "Отключена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
