# Generated by Django 5.1.2 on 2024-11-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("successfully", "Успешно"),
                    ("not_successfully", "Не успешно"),
                ],
                default="created",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
    ]
