# Generated by Django 5.1.2 on 2024-11-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_mailing_owner_mailingattempt_owner_message_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["date_time_attempt"],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
    ]
