# Generated by Django 5.1.2 on 2024-11-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0009_alter_mailingattempt_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["date_first_message", "message"],
                "permissions": [
                    ("can_view_other_mailing", "Может просматривать чужие рассылки"),
                    ("can_mailing_blocked", "Может блокировать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["theme_message"],
                "permissions": [
                    ("can_view_other_message", "Может просматривать чужие сообщения")
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["full_name"],
                "permissions": [
                    ("can_view_other_client", "Может просматривать чужих клиентов")
                ],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="date_time_attempt",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время попытки"
            ),
        ),
    ]
