# Generated by Django 5.1.2 on 2024-11-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0011_usermailingstatistics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("successfully", "Успешно"),
                    ("not_successfully", "Не успешно"),
                ],
                default="not_successfully",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
        migrations.DeleteModel(
            name="UserMailingStatistics",
        ),
    ]
