# Generated by Django 5.1.2 on 2024-11-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0012_alter_mailingattempt_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
