# Generated by Django 5.1.2 on 2024-11-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0013_mailing_is_blocked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "Создана"),
                    ("running", "Запущена"),
                    ("completed", "Завершена"),
                    ("blocked", "Заблокирована"),
                    ("unblocked", "Разблокирована"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
