# Generated by Django 5.1.2 on 2024-11-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0015_alter_recipient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["full_name"],
                "permissions": [
                    ("can_view_other_client", "VVМожет просматривать чужих клиентов")
                ],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
